### ISSUE TITLE
Use SolverCore 0.3 `solve!`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/Percival.jl#101]
This is a todo-list to bump Percival to SolverCore 0.3 and go to 0-allocations.

- [x] Add solver structure https://github.com/JuliaSmoothOptimizers/Percival.jl/pull/80
- [x] bump SolverCore 0.3 (change the stats constructor)
- [x] use `solve!(solver, nlp, stats)` pre-allocating `stats`
- [x] test reuse workspace #104 
- [x] pre-allocate structure for `cgls`
- [x] pre-allocate `TronSolver` structure
- [x] Add `verbose` integer
- [x] Add `callback`
- [x] pre-allocate model `AugLagModel`
- [ ] add allocation test
